# Generated by Django 5.2.1 on 2025-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='B.Tech', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('IN', 'Internship'), ('CT', 'Contract')], default='FT', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
